unbind C-b
set-option -g prefix C-b
set-option -g prefix M-m
bind-key C-a send-prefix

set-option -g focus-events on
set -g history-limit 25000
setw -g mouse on
set -g status-style 'bg=#333333 fg=#5eacd3'
set -g base-index 1
setw -g pane-base-index 1
set -sg escape-time 0

set -ga terminal-overrides ",*256col*:Tc"
set -g default-terminal "screen-256color"

bind-key -r f run-shell "tmux neww ~/dotfiles/tools/tmux-sessionizer.sh"
bind-key -n C-\\ run-shell "tmux neww ~/dotfiles/tools/tmux-sessionizer.sh"
bind-key -r e run-shell "tmux neww ~/dotfiles/tools/tmux-sessionizer-git-worktree.sh"

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind -r ^ last-window
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/personal/dev/todo.md"

bind -r C-f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind -r M-q run-shell "tmux neww tmux-sessionizer -s 0"
bind -r M-w run-shell "tmux neww tmux-sessionizer -s 1"
bind -r M-e run-shell "tmux neww tmux-sessionizer -s 2"
bind -r M-r run-shell "tmux neww tmux-sessionizer -s 3"

bind -r M-s run-shell "tmux split-window -h ascii-video-player ~/personal/dev/subway_surfer/frames"

