local telescope = require("telescope")

telescope.load_extension("project")
telescope.load_extension("fzf")
require("git-worktree").setup({})
telescope.load_extension("git_worktree")
telescope.load_extension("lazygit")
telescope.load_extension("dap")
telescope.load_extension("refactoring")
telescope.load_extension("gh")
