#!/usr/bin/bash

set -euo pipefail

if [[ ! -d "$HOME/git/yay-bin" ]]; then
    pushd git
    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay-bin.git
    pushd yay-bin
    makepkg -si
    popd
    popd
else
    echo "yay installed, skipped."
fi

sudo pacman -S --needed --noconfirm tmux
sudo pacman -S --needed --noconfirm fd
sudo pacman -S --needed --noconfirm go

yay -S --noconfirm --needed fzf
# Switch to nvm
yay -S --noconfirm --needed nodejs npm bun
yay -S --noconfirm --needed go
yay -S --noconfirm --needed gimp
yay -S --noconfirm --needed stylua
