#!/usr/bin/bash

set -euo pipefail

mkdir -p ~/git
if [[ ! "command -v yay" ]]; then
    pushd ~/git
    sudo pacman -S --needed --noconfirm git base-devel
    git clone https://aur.archlinux.org/yay-bin.git
    pushd yay-bin
    makepkg -si
    popd
    popd
else
    echo "yay installed, skipped."
fi

sudo pacman -S --needed --noconfirm tmux
sudo pacman -S --needed --noconfirm fd
sudo pacman -S --needed --noconfirm go


yay -S --noconfirm --needed fzf

# TODO Switch to nvm
yay -S --noconfirm --needed nodejs npm bun
sudo pacman -S --needed --noconfirm pnpm

yay -S --noconfirm --needed go
yay -S --noconfirm --needed gimp
yay -S --noconfirm --needed stylua
