#!/bin/bash

set -uo pipefail

lines=$(mktemp)

bt list >>$lines
wmctrl -l >>$lines

selection=$(cat $lines | rofi -dmenu -i)
if [[ -z "$selection" ]]; then
    echo "No selection made."
    exit 0
fi

# line comes from Browser Tabs
if [[ "$selection" =~ ^a\.[0-9]\.[0-9]+ ]]; then
    tabID=$(echo "$selection" | awk '{print $1}')
    window_title=$(echo "$selection" | awk '{print $1=""; print $0}' | grep -oE "[a-zA-Z0-9]{2,}.*")
    bt activate $tabID
else
    # line comes from wmctrl
    window_title=$(echo "$selection" | awk '{print $1=$2=$3=""; print $0}')
fi

wmctrl -a $window_title

rm "$lines"
