#!/bin/bash

set -euo pipefail

if [[ $(uname -a) == *"arch"* ]]; then
    echo "Running pacman -Syu"
    sudo pacman -Syu
elif [[ $(uname -a) == *"ubuntu"* ]]; then
    echo "Running apt update and upgrade"
    sudo apt update
    sudo apt upgrade
fi
